# Generated by Django 3.1.7 on 2021-03-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_cinema_cinemahall_cinemaseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='cinemahall',
            old_name='cinema_id',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='cinemaseat',
            old_name='cinemal_hall_id',
            new_name='cinema_hall',
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking')),
                ('cinema_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cinemaseat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cinemahall'),
        ),
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.show'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
